Correlation structures are the core of DHG
Currently, DHG’s low-order structures include graph, directed graph, and bipartite graph. In the future, we will add more low-order structures.

Construct a graph from edge list with dhg.Graph:

In [25]:
import dhg
import torch

In [2]:
g = dhg.Graph(5, [(0, 1), (0, 2), (1, 2), (3, 4)])
g

Graph(num_v=5, num_e=4)

In [3]:
g.v

[0, 1, 2, 3, 4]

In [4]:
g.e

([(0, 1), (0, 2), (1, 2), (3, 4)], [1.0, 1.0, 1.0, 1.0])

In [6]:
e_list, e_weight = g.e
e_list

[(0, 1), (0, 2), (1, 2), (3, 4)]

In [7]:
e_weight

[1.0, 1.0, 1.0, 1.0]

In [8]:
g.e_both_side

([(0, 1), (0, 2), (1, 2), (3, 4), (1, 0), (2, 0), (2, 1), (4, 3)],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

In [13]:
# print the adjacency matrix
print(g.A, "\n")
print(g.A.to_dense())

tensor(indices=tensor([[0, 0, 1, 1, 2, 2, 3, 4],
                       [1, 2, 0, 2, 0, 1, 4, 3]]),
       values=tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
       size=(5, 5), nnz=8, layout=torch.sparse_coo) 

tensor([[0., 1., 1., 0., 0.],
        [1., 0., 1., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]])


Edges automatically merge duplicates

In [14]:
g = dhg.Graph(5, [(0, 1), (0, 2), (2, 0), (3, 4)])
g.e

([(0, 1), (0, 2), (3, 4)], [1.0, 1.0, 1.0])

In [15]:
g.add_edges([(0, 1), (4, 3)])
g.e

([(0, 1), (0, 2), (3, 4)], [1.0, 1.0, 1.0])

Reduced from High-Order Structures

In [16]:
# Define a Hyper Graph
hg = dhg.Hypergraph(5, [(0, 1, 2), (1, 3, 2), (1, 2), (0, 3, 4)])
hg.e

([(0, 1, 2), (1, 2, 3), (1, 2), (0, 3, 4)], [1.0, 1.0, 1.0, 1.0])

In [17]:
# print hypergraph incidence matrix
hg.H.to_dense()

tensor([[1., 0., 0., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 0., 1.]])

In [18]:
# Star Expansion
g, v_mask = dhg.Graph.from_hypergraph_star(hg)
g

Graph(num_v=9, num_e=11)

In [19]:
g.e[0]

[(0, 5),
 (0, 8),
 (1, 5),
 (1, 6),
 (1, 7),
 (2, 5),
 (2, 6),
 (2, 7),
 (3, 6),
 (3, 8),
 (4, 8)]

In [20]:
v_mask

tensor([ True,  True,  True,  True,  True, False, False, False, False])

In [21]:
g.A.to_dense()

tensor([[0., 0., 0., 0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 1., 0., 0., 0., 0.]])

In [22]:
#Clique Expansion
g = dhg.Graph.from_hypergraph_clique(hg)
g

Graph(num_v=5, num_e=8)

In [23]:
g.e

([(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3), (3, 4)],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

In [24]:
g.A.to_dense()

tensor([[0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 0.],
        [1., 1., 0., 1., 0.],
        [1., 1., 1., 0., 1.],
        [1., 0., 0., 1., 0.]])

In [26]:
# HyperGCN-based Expansion
X = torch.tensor(([[0.6460, 0.0247],
                       [0.9853, 0.2172],
                       [0.7791, 0.4780],
                       [0.0092, 0.4685],
                       [0.9049, 0.6371]]))
g = dhg.Graph.from_hypergraph_hypergcn(hg, X)
g

Graph(num_v=5, num_e=4)

In [27]:
g.e

([(0, 2), (2, 3), (1, 2), (3, 4)],
 [0.3333333432674408, 0.3333333432674408, 0.5, 0.3333333432674408])

In [28]:
g.A.to_dense()

tensor([[0.0000, 0.0000, 0.3333, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.0000, 0.0000],
        [0.3333, 0.5000, 0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.3333, 0.0000, 0.3333],
        [0.0000, 0.0000, 0.0000, 0.3333, 0.0000]])

In [29]:
g = dhg.Graph.from_hypergraph_hypergcn(hg, X, with_mediator=True)
g

Graph(num_v=5, num_e=5)

In [30]:
g.e

([(1, 2), (0, 2), (2, 3), (0, 4), (0, 3)],
 [0.6666666865348816,
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408])

In [31]:
g.A.to_dense()

tensor([[0.0000, 0.0000, 0.3333, 0.3333, 0.3333],
        [0.0000, 0.0000, 0.6667, 0.0000, 0.0000],
        [0.3333, 0.6667, 0.0000, 0.3333, 0.0000],
        [0.3333, 0.0000, 0.3333, 0.0000, 0.0000],
        [0.3333, 0.0000, 0.0000, 0.0000, 0.0000]])

Construct a bipartite graph from hypergraph with dhg.BiGraph.from_hypergraph()

In [32]:
hg = dhg.Hypergraph(5, [(0, 1, 2), (1, 3, 2), (1, 2), (0, 3, 4)])
hg.e
# print hypergraph incidence matrix
hg.H.to_dense()

tensor([[1., 0., 0., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 0., 1.]])

In [33]:
g = dhg.BiGraph.from_hypergraph(hg, vertex_as_U=True)
g

Bipartite Graph(num_u=5, num_v=4, num_e=11)

In [35]:
g.B.to_dense()

tensor([[1., 0., 0., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 0., 1.]])

In [36]:
g = dhg.BiGraph.from_hypergraph(hg, vertex_as_U=False)
g

Bipartite Graph(num_u=4, num_v=5, num_e=11)

In [37]:
g.B.to_dense()

tensor([[1., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 0., 0.],
        [1., 0., 0., 1., 1.]])

Graph to Hypergraph using dhg.Hypergraph.from_graph()

In [42]:
g = dhg.Graph(5, [(0, 1), (1, 2), (2, 3), (1, 4)])
hg = dhg.Hypergraph.from_graph(g)
hg.H.to_dense()

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 1.],
        [0., 1., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Construct a hypergraph from vertex’s k-Hop neighbors of a graph with dhg.Hypergraph.from_graph_kHop()

In [43]:
g = dhg.Graph(5, [(0, 1), (1, 2), (2, 3), (1, 4)])
hg = dhg.Hypergraph.from_graph_kHop(g, k=1)
hg.H.to_dense()
hg = dhg.Hypergraph.from_graph_kHop(g, k=2)
hg.H.to_dense()

tensor([[1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 1., 1.],
        [1., 1., 0.]])

Construct a hypergraph from a bipartite graph with dhg.Hypergraph.from_bigraph()

In [ ]:
g = dhg.BiGraph(4, 3, [(0, 1), (1, 1), (2, 1), (3, 0), (1, 2)])
hg = dhg.Hypergraph.from_bigraph(g, U_as_vertex=True)
hg = dhg.Hypergraph.from_bigraph(g, U_as_vertex=False)